
### login to account
post http://localhost:3000/api/auth/login 


### register account 
post http://localhost:3000/api/auth/register 


### logout account 
post http://localhost:3000/api/auth/logout 




